### PR TITLE
Small bug

### PR DESCRIPTION
**Pull request by heyner29**
I am trying to update my personal project to the latest version and on the way I found this little bug
Captura de pantalla de 2019-09-28 01-09-12

### CODE REVIEW

**Comment by aocneanu** [comment]
I guess you should upgrade PHP to 7.3 ;)

**Comment by heyner29** [comment]
Hello, I already made the PHP update to 7.3 but I still have problems loading the relationships :( ¿Do you know by chance if I should do something else?

Captura de pantalla de 2019-09-30 11-37-59


Captura de pantalla de 2019-09-30 11-32-47

**Comment by aocneanu** [comment]
you should check your php version with `phpinfo()` instead of `php -v` (which returns the cli version)

**Comment by heyner29** [comment]
I already solved, the problem comes from Valet / Linux, with updating the package and restarting the services everything worked correctly!.
Thanks again

**Pull request merged**
